# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modoboa_public_api', '0004_auto_20160614_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='modoboainstance',
            name='domain_alias_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
