# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-01 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modoboa_public_api', '0006_auto_20161226_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modoboaextension',
            name='version',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='modoboainstance',
            name='known_version',
            field=models.CharField(max_length=30),
        ),
    ]
