# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-01 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modoboa_public_api', '0007_auto_20180201_1440'),
    ]

    operations = [
        migrations.RenameField(
            'modoboaextension', 'new_version', 'version'
        ),
        migrations.RenameField(
            'modoboainstance', 'new_known_version', 'known_version'
        ),
    ]
