# Generated by Django 4.2.9 on 2024-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modoboa_public_api', '0008_auto_20180201_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='modoboaextension',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modoboainstance',
            name='known_version',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
