# Generated by Django 5.2.17 on 2026-09-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modoboa_public_api', '0009_modoboaextension_deprecated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modoboaextension',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modoboaextension',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modoboaextension',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='modoboaextension',
            constraint=models.UniqueConstraint(condition=models.Q(('is_core', True)), fields=('is_core',), name='unique_core_component'),
        ),
    ]
